version: '2'
services:
  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
     - "7000:80"
    volumes: 
     - "./:/www"
     - "./site.conf:/etc/nginx/conf.d/site.conf"
    links:
    - php
  php:
    image: php:7.3-fpm
    container_name: php-fpm
    volumes:
      - "./:/www"
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"